import { writeFileSync } from "node:fs";
import { profile } from "../src/data/profile.js";
import { projects } from "../src/data/projects.js";
import { experience } from "../src/data/experience.js";
import { skillGroups } from "../src/data/skills.js";

const assetVersion = "2026-05-16-contact-fix";

const escapeHtml = (value = "") =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");

const demoVideoPoster = "https://img.youtube.com/vi/avCUaiDe2zA/maxresdefault.jpg";
const demoVideoPath = "media/early-technical-demo.mp4";

const listItems = (items) =>
  items.map((item) => `<li>${escapeHtml(item)}</li>`).join("\n");

const tagList = (items) =>
  items.map((item) => `<span class="tag">${escapeHtml(item)}</span>`).join("\n");

const highlights = profile.highlights
  .map(
    (item) => `
      <article class="highlight">
        <strong>${escapeHtml(item.label)}</strong>
        <span>${escapeHtml(item.detail)}</span>
        ${
          item.link
            ? `<a class="text-link" href="${escapeHtml(item.link)}" target="_blank" rel="noreferrer">${escapeHtml(item.linkLabel || "View credential")}</a>`
            : ""
        }
      </article>`
  )
  .join("\n");

const caseStudies = projects
  .map(
    (project) => `
      <article class="case-card">
        <div class="case-card__header">
          <span class="eyebrow">${escapeHtml(project.eyebrow)}</span>
        </div>
        <h3>${escapeHtml(project.title)}</h3>
        <p>${escapeHtml(project.summary)}</p>
        <ul>${listItems(project.impact)}</ul>
        <div class="tag-row">${tagList(project.stack)}</div>
        ${
          project.link
            ? `<a class="text-link" href="${escapeHtml(project.link)}" target="_blank" rel="noreferrer">View public repository</a>`
            : ""
        }
      </article>`
  )
  .join("\n");

const timeline = experience
  .map(
    (job) => `
      <article class="timeline-item">
        <div class="timeline-marker" aria-hidden="true"></div>
        <div>
          <span class="eyebrow">${escapeHtml(job.dates)} | ${escapeHtml(job.location)}</span>
          <h3>${escapeHtml(job.role)}</h3>
          <p class="company">${escapeHtml(job.company)}</p>
          <ul>${listItems(job.points)}</ul>
        </div>
      </article>`
  )
  .join("\n");

const skills = skillGroups
  .map(
    (group) => `
      <article class="skill-card">
        <h3>${escapeHtml(group.name)}</h3>
        <div class="tag-row">${tagList(group.skills)}</div>
      </article>`
  )
  .join("\n");

const profiles = [
  {
    label: "LinkedIn",
    detail: "My professional profile",
    url: profile.links.linkedin,
  },
  {
    label: "GitHub",
    detail: "My public repositories and code samples",
    url: profile.links.github,
  },
  {
    label: "Credly",
    detail: "My certification profile",
    url: profile.links.credly,
  },
  {
    label: "TryHackMe",
    detail: "My account for hands-on cybersecurity learning",
    url: profile.links.tryHackMe,
  },
];

const profileCards = profiles
  .map(
    (item) => `
      <a class="profile-card" href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">
        <strong>${escapeHtml(item.label)}</strong>
        <span>${escapeHtml(item.detail)}</span>
      </a>`
  )
  .join("\n");

const html = `<!-- Generated by scripts/build-site.mjs. Edit src/data/*.js and rebuild. -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="referrer" content="strict-origin-when-cross-origin" />
    <meta
      name="description"
      content="${escapeHtml(profile.summary)}"
    />
    <title>${escapeHtml(profile.name)} | ${escapeHtml(profile.title)}</title>
    <link rel="icon" href="img/globe.png" type="image/png" />
    <link rel="stylesheet" href="style.css?v=${assetVersion}" />
    <script>
      try {
        const savedTheme = localStorage.getItem("theme");
        const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
        document.documentElement.dataset.theme = savedTheme || (prefersDark ? "dark" : "light");
      } catch {
        document.documentElement.dataset.theme = "light";
      }
    </script>
  </head>
  <body>
    <header class="site-header">
      <a class="brand" href="#top" aria-label="${escapeHtml(profile.name)} homepage">
        <span class="brand-mark" aria-hidden="true">GG</span>
        <span>${escapeHtml(profile.name)}</span>
      </a>
      <nav class="nav-links" aria-label="Main navigation">
        <a href="#proof">Highlights</a>
        <a href="#projects">Projects</a>
        <a href="#experience">Experience</a>
        <a href="#skills">Skills</a>
        <a href="#profiles">Profiles</a>
        <a href="#demo">Demo</a>
        <a href="#contact">Contact</a>
      </nav>
      <button class="theme-toggle" id="themeToggle" type="button" aria-label="Toggle dark mode">
        <span aria-hidden="true">Mode</span>
      </button>
    </header>

    <main id="top">
      <section class="hero" aria-labelledby="hero-title">
        <div class="hero__content">
          <p class="eyebrow">${escapeHtml(profile.location)}</p>
          <h1 id="hero-title">${escapeHtml(profile.name)}</h1>
          <p class="hero__title">${escapeHtml(profile.title)}</p>
          <p class="hero__summary">${escapeHtml(profile.summary)}</p>
          <div class="button-row">
            <a class="button button--primary" href="${escapeHtml(profile.resumePath)}" download>Download Resume</a>
            <a class="button" href="#projects">View Projects</a>
          </div>
        </div>
      </section>

      <section class="section" id="proof" aria-labelledby="proof-title">
        <div class="section-heading">
          <p class="eyebrow">Highlights</p>
          <h2 id="proof-title">Credentials and technical focus</h2>
          <p>A snapshot of the education, certifications, and hands-on areas I bring into network and security work.</p>
        </div>
        <div class="highlight-grid">
          ${highlights}
        </div>
      </section>

      <section class="section section--muted" id="projects" aria-labelledby="projects-title">
        <div class="section-heading">
          <p class="eyebrow">Featured Work</p>
          <h2 id="projects-title">Selected projects and workstreams</h2>
          <p>A few examples of how I approach automation, analytics, and security problems in practical environments.</p>
        </div>
        <div class="case-grid">
          ${caseStudies}
        </div>
      </section>

      <section class="section" id="experience" aria-labelledby="experience-title">
        <div class="section-heading">
          <p class="eyebrow">Experience Timeline</p>
          <h2 id="experience-title">Recent roles</h2>
          <p>A concise view of the roles that shaped my cybersecurity, network operations, automation, and IT support experience.</p>
        </div>
        <div class="timeline">
          ${timeline}
        </div>
      </section>

      <section class="section section--muted" id="skills" aria-labelledby="skills-title">
        <div class="section-heading">
          <p class="eyebrow">Skills</p>
          <h2 id="skills-title">Technical toolkit</h2>
          <p>Grouped around the kinds of problems I enjoy working on: secure networks, operational tooling, and repeatable analysis.</p>
        </div>
        <div class="skill-grid">
          ${skills}
        </div>
      </section>

      <section class="section" id="profiles" aria-labelledby="profiles-title">
        <div class="section-heading">
          <p class="eyebrow">Profiles</p>
          <h2 id="profiles-title">Where to verify and explore more</h2>
          <p>These links collect my public technical footprint separately from direct contact.</p>
        </div>
        <div class="profile-grid">
          ${profileCards}
        </div>
      </section>

      <section class="section video-section" id="demo" aria-labelledby="demo-title">
        <div class="section-heading">
          <p class="eyebrow">Early Technical Demo</p>
          <h2 id="demo-title">Where the curiosity started</h2>
          <p>This older educational demo is part of my learning path: exploring debugging tools, game memory behavior, and how software state can be inspected safely in a controlled environment.</p>
        </div>
        <video
          class="demo-video"
          controls
          preload="metadata"
          poster="${demoVideoPoster}"
        >
          <source src="${demoVideoPath}" type="video/mp4" />
          Your browser does not support the video player.
          <a href="https://www.youtube.com/watch?v=avCUaiDe2zA">Watch the demo on YouTube</a>.
        </video>
      </section>

      <section class="contact-section" id="contact" aria-labelledby="contact-title">
        <div>
          <p class="eyebrow">Resume + Contact</p>
          <h2 id="contact-title">Let us make the next conversation easy.</h2>
          <p>Download my current resume or reach me directly by email.</p>
        </div>
        <div class="contact-panel">
          <div class="contact-actions">
            <a class="button button--primary" href="${escapeHtml(profile.resumePath)}" download>Download Resume</a>
            <button
              class="button"
              id="copyEmailButton"
              type="button"
              data-email="${escapeHtml(profile.email)}"
              data-default-label="Copy Email"
            >
              Copy Email
            </button>
          </div>
          <p class="contact-email">${escapeHtml(profile.email)}</p>
        </div>
      </section>
    </main>

    <footer class="site-footer">
      <span>&copy; <span id="year"></span> ${escapeHtml(profile.name)}</span>
      <a href="#top">Back to top</a>
    </footer>

    <script src="script.js?v=${assetVersion}"></script>
  </body>
</html>
`;

writeFileSync(new URL("../index.html", import.meta.url), html);
console.log("Generated index.html from centralized src/data content.");
